### ISSUE TITLE
Использование полей класса в его методах

### ISSUE THREAD

**Issue by sergregory** [Dashia18/Simple_fraction_class#1]
``` cpp
int Simple_fraction::get_numerator(){
    return Simple_fraction::numerator;
}
```

при обращении к полю класса внутри методов этого класса пространство имён указывать не обязательно, то есть будет работать и такой код:

``` cpp
int Simple_fraction::get_numerator(){
    return numerator;
}
```

**Comment by Dashia18** [comment]
Это сделала.
int Simple_fraction::get_numerator(){
    return numerator;
}
Конечно все равно много раз приходится это писать Simple_fraction:: . Но если тут не надо, то значительно меньше.
