### ISSUE TITLE
Compatibility with standard

### ISSUE THREAD

**Issue by sergregory** [Dashia18/Simple_fraction_class#5]
`abs` function is specified in header `<cstdlib>` for int/long/etc and in header `<cmath>` for float and double. In both cases it is wrapped into the namespace std. MSVS allows to use this function just by including `<math.h>` header, but more correct way is to include one of `<cstdlib>` or `<cmath>` (these a c++ names for c headers `stdlib.h` and `math.h`, correspondingly) and call this function as `std::abs` or use `using namespace std`  directive.
[cppreference.com: abs(int)](http://en.cppreference.com/w/cpp/numeric/math/abs)
[cppreference.com: abs(float)](http://en.cppreference.com/w/cpp/numeric/math/fabs)

P.S. on linux I just can't build the project without these modifications...

**Comment by Dashia18** [comment]
То есть лучше писать для математических функций, например таких как модуль abs, заголовочный файл, например, <cmath> (для float и double) или <cstdlib> (int/long/etc). Иначе не везде работает. А если использовать одну из этих для всех типов?

**Comment by sergregory** [comment]
Ну нужно подключать заголовочный файл где объявлены эти функции.. Просто студия и так компилирует, но вообще говоря не должна, а если подключишь то везде будет работать.

В принципе да, можно подключить только тот, где объявлены эти функции для типов с плавающей точкой, но тогда если ты будет в функцию передавать int и результат присваивать инту, компилятор будет выдавать предупреждение что ты сужаешь тип переменной.

**Comment by Dashia18** [comment]
В общем я поняла, что бы не было предупреждений, надо использовать для каждого типа свою библиотеку. Просто иногда сложно запомнить какую нужную для каждого типа. Я думала для таких функций math.h достаточно.

**Comment by sergregory** [comment]
Я тоже думал её достаточно, но вот оказалось что нет) сам из интернета узнал
